In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sn



In [2]:
train=pd.read_csv('train.csv')
train.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
test=pd.read_csv('test.csv')
test.head(5)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [4]:
print(train.shape)
print(test.shape)

(42000, 785)
(28000, 784)


In [5]:
y_train=train['label']
x_train=train.drop(['label'],axis=1)
x_test= test

x_train.shape, x_test.shape, y_train.shape


((42000, 784), (28000, 784), (42000,))

In [6]:
y_train

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [7]:
x_train = x_train.values.reshape(x_train.shape[0], 28, 28, 1) #or we can use -1 on the place of x_train.shape
x_train=x_train/255.0
x_test = x_test.values.reshape(x_test.shape[0], 28, 28, 1)
x_test=x_test/255.0

In [8]:
x_train.shape, x_test.shape

((42000, 28, 28, 1), (28000, 28, 28, 1))

In [9]:
#One Hot Encoding 
y_train= keras.utils.to_categorical(y_train,10)
y_train.shape

(42000, 10)

In [10]:
#Printing original labels 
print(train['label'].head()) 

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64


In [11]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [12]:
print(y_train[0:5,:])

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
model = tf.keras.models.Sequential ([

tf.keras.layers.Conv2D(32,(3,3), activation = 'relu', input_shape=(28,28,1)), 
tf.keras.layers. Conv2D(32, (3,3), activation = 'relu'),
tf.keras.layers. MaxPooling2D(2,2),
tf. keras.layers.Conv2D(64, (3,3), activation = "relu", padding = 'Same'), 
tf.keras.layers.Conv2D(64, (3,3), activation = 'relu', padding = 'Same'),
tf. keras.layers. MaxPooling2D(pool_size = (2,2), strides = (2,2)),
tf.keras.layers.Dropout (0.25),
tf.keras.layers.Conv2D(64, (3,3), activation ="relu", padding= "Same"),
tf.keras. layers.Conv2D(64, (3,3), activation = 'relu', padding = 'Same'), 
tf.keras.layers. MaxPooling2D(pool_size = (2,2), strides = (2,2)),
tf.keras.layers.Dropout (0.25),
tf.keras.layers. Flatten(),
tf.keras.layers.Dense(256, activation='relu'),
#tf.keras.layers.Dropout(0.58),
tf.keras.layers.Dense(256, activation='relu'),
tf.keras.layers.Dropout (0.50), 
tf.keras.layers.Dense(10, activation='softmax')

])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 32)        9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 12, 12, 64)        18496     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 64)        36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
dropout (Dropout)            (None, 6, 6, 64)          0

In [14]:
#Defining the callback function to stop our training once the acceptable accuracy is reached

class myCallback(keras.callbacks.Callback):
    def on_end_epoch(self,epoch,logs={}):
        if(logs.get('accuracy')>0.999):
            print("\n Reached 99.9% accuracy so cancelling our training! ")
            self.model.stop_training= True
callbacks= myCallback()

In [15]:
#Compiling and model training with batch size = 50, epochs=20 and optimizer =adam

Optimizer= keras.optimizers.Adam(
            learning_rate=0.0005,
            beta_1=0.9,
            beta_2=0.999,
            epsilon=1e-07,
            name='Adam'
)

model.compile(optimizer=Optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=50, epochs=20, callbacks=[callbacks])

Epoch 1/20
840/840 [==============================] - 243s 290ms/step - loss: 0.3453 - accuracy: 0.8848
Epoch 2/20
840/840 [==============================] - 237s 282ms/step - loss: 0.0829 - accuracy: 0.9746
Epoch 3/20
840/840 [==============================] - 249s 297ms/step - loss: 0.0569 - accuracy: 0.9829
Epoch 4/20
840/840 [==============================] - 250s 298ms/step - loss: 0.0481 - accuracy: 0.9858
Epoch 5/20
840/840 [==============================] - 249s 297ms/step - loss: 0.0386 - accuracy: 0.9886
Epoch 6/20
840/840 [==============================] - 250s 297ms/step - loss: 0.0350 - accuracy: 0.9895
Epoch 7/20
840/840 [==============================] - 239s 285ms/step - loss: 0.0308 - accuracy: 0.9908
Epoch 8/20
840/840 [==============================] - 242s 288ms/step - loss: 0.0272 - accuracy: 0.9919
Epoch 9/20
840/840 [==============================] - 249s 296ms/step - loss: 0.0258 - accuracy: 0.9927
Epoch 10/20
840/840 [==============================] - 250s 297m

In [17]:
results= model.predict(x_test)

#to select the indexes with the maximum probability
results= np.argmax(results,axis=1)
results=pd.Series(results,name="Label")

In [18]:
submission= pd.concat([pd.Series(range(1,28001),name="ImageId"),results],axis=1)

submission.to_csv("submission.csv",index=False)

In [19]:
!kaggle competitions submit -c digit-recognizer -f submission.csv -m "Submission 1"

Successfully submitted to Digit Recognizer



  0%|          | 0.00/235k [00:00<?, ?B/s]
  3%|3         | 8.00k/235k [00:00<00:10, 22.6kB/s]
 37%|###7      | 88.0k/235k [00:00<00:04, 31.8kB/s]
 51%|#####1    | 120k/235k [00:00<00:02, 43.2kB/s] 
100%|##########| 235k/235k [00:08<00:00, 28.0kB/s]
